#!/bin/bash         
file=$1
outfile=$2
LAMMPS_HOME="/home/projesh/lammps"
CUDA_HOME="/usr/local/cuda"
MPI_HOME="/home/projesh/openmpi-4.1.5/build_gpu/bin"

cp ${file} temp.cpp
cp ${outfile} temp.exe

${MPI_HOME}/mpicxx  -std=c++14 \
-I ./include/Eigen_3.3.1/ \
-I${LAMMPS_HOME}/src/ \
-L${LAMMPS_HOME}/src/ \
-L${LAMMPS_HOME}/lib/gpu/ \
-L${LAMMPS_HOME}/lib/colvars/ \
-L${LAMMPS_HOME}/src/STUBS/ \
-L${CUDA_HOME}/lib64 \
-L${CUDA_HOME}/lib64/stubs \
-o ${outfile} temp.cpp -lm -fopenmp -g3 -w -llammps_omp -ldl -lgpu -lmpi_stubs -lmpi -lpthread  -lcudart -lcuda -lcolvars
